// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArry62Z6gOmzJFFdX1Q6o1Yu6I5Gs3dS4',
    appId: '1:383639778289:web:90ac5df878ce2c739fca50',
    messagingSenderId: '383639778289',
    projectId: 'messenger-5b9f8',
    authDomain: 'messenger-5b9f8.firebaseapp.com',
    storageBucket: 'messenger-5b9f8.appspot.com',
    measurementId: 'G-JNKZ9VN939',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaJKbLJloz1341NxogKaMbcg-iM4WUrxo',
    appId: '1:383639778289:android:cde8b0292bd49b119fca50',
    messagingSenderId: '383639778289',
    projectId: 'messenger-5b9f8',
    storageBucket: 'messenger-5b9f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZvFsNkZL0m8OaIebW1NpZffaZEGxmE6A',
    appId: '1:383639778289:ios:538f7d6bde4a09549fca50',
    messagingSenderId: '383639778289',
    projectId: 'messenger-5b9f8',
    storageBucket: 'messenger-5b9f8.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZvFsNkZL0m8OaIebW1NpZffaZEGxmE6A',
    appId: '1:383639778289:ios:a08bdbdbe731aebf9fca50',
    messagingSenderId: '383639778289',
    projectId: 'messenger-5b9f8',
    storageBucket: 'messenger-5b9f8.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
